#ifndef CONST_H
#define CONST_H


#define NUM_OF_ITEMS_MAIN_MENU 5
#define NUM_OF_ITEMS_CONFIG_MENU 4
#define NUM_OF_ITEMS_NEW_MENU 3
#define NUM_OF_ITEMS_RESULTS_MENU 4




#define MAX_MENU_ITEM_SIZE 50
#define NUM_OF_MENUS 2

#endif